### ISSUE TITLE
Why reuse GRU in seq2seq with attention?

### ISSUE THREAD

**Issue by chenzhekl** [spro/practical-pytorch#10]
It seems the same `GRU` module is reused for all layers in both encoder and decoder. What is the design choice behind that? Wouldn't it be more reasonable to use `GRU` with parameters `num_layers` (i.e. separate parameters for each layer) or one `GRUCell` per layer?

**Comment by spro** [comment]
I was convinced it was quicker to converge (likely because of fewer parameters to train) but haven't been able to replicate those results. I agree it would be more reasonable to stick to using `num_layers` normally - there's an update on the way.

**Comment by spro** [comment]
This is resolved with 920d98b3dad3dac5323ccbe9ba44cd0c35331fc1 using
