### ISSUE TITLE
can't import torch

### ISSUE THREAD

**Issue by Little-Pr1nce** [spro/practical-pytorch#131]
macbook pro
using " pip install torch torchvison" to install pytorch
but when i run the project it shows:
ImportError: dlopen(/Users/little-prince/Documents/Graduation_Project/venv/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/little-prince/Documents/Graduation_Project/venv/lib/python3.6/site-packages/torch/lib/libshm.dylib
  Reason: image not found

how do i deal with it

**Comment by jiasureZ** [comment]
Have you solved it? Can you tell me how to do?

**Comment by jiasureZ** [comment]
brew install libomp solves the problem.
