### ISSUE TITLE
I can't calculate the score of attention in Seq2Seq Translation.

### ISSUE THREAD

**Issue by beebrain** [spro/practical-pytorch#135]
I can't calculate the score of the attention that provided the error like this.
 
![image](https://user-images.githubusercontent.com/10016227/62998577-2cf2eb00-be96-11e9-919d-1cf76c961d44.png)

The implementation tries to calculate the attention score step by step but why do not they use dot operation instance mm or bmm operation.
The shape of hidden is [1,256] and  energy is [1,256] 
We need transpose hidden and multiple with energy.
If I wrong, please suggest me to fix that.

**Comment by xiaolan98** [comment]
The forty-fourth line should be energy = hidden.view(-1).dot(energy.view(-1))

**Comment by beebrain** [comment]
@xiaolan98  Thank you, I fixed with mm operation. 
My code is "energy = hidden.mm(ennergy.transpose(0,1)". Is it ok? 
I think that is a summation of the product.
