### ISSUE TITLE
[Attention model structure]

### ISSUE THREAD

**Issue by RangoHU** [spro/practical-pytorch#16]
Hello,

Thanks for the nice tutorial! I have a question on the structure of the attention encoder you plot in the tutorial.

In the tutorial, the attn_weights is computed using two parts: 1) previous hidden states of the encoder, and 2) the embedding vector of input (a word in this case). Then the attn_weight is applied on the encoder outputs, which are a bunch of hidden states. 

But according to the [paper](https://arxiv.org/pdf/1409.0473v6.pdf) that proposes the attention model, the attn_weights are computed from 1) previous hidden states of the encoder, and 2) all the outputs of the decoder.  Could you explain why you implement the model differently? Thanks!

**Comment by spro** [comment]
I don't have a great reason why I implemented it differently, other than it worked well. There are definitely some confusing differences that I will clear up with an update soon.

The biggest difference is that in the Bahdanau paper, the attention weights are calculated from the state before the output layer `s_{i-1}`, whereas I'm using the final output value `y_{i-1}`. It's also confusing that they call `s` the RNN "hidden" state, while I call that the RNN "output" and make a distinction between that and "internal hidden state" of the RNN.

So I think it's more like I'm using 1) previous hidden states of encoder and 2) previous output of decoder, while they're using 1) previous hidden states of encoder and 2) previous hidden state of decoder.

**Comment by spro** [comment]
By the way this model could be considered a bit closer to the simpler "global" models implemented in [Effective Approaches to Attention-based Neural Machine Translation](https://arxiv.org/abs/1508.04025)

**Comment by spro** [comment]
I updated the tutorial to match the model from the "Effective Approaches" paper, while also explaining the Bahdanau model in more detail. See 2fd4c11cf1be84725b65f656043e3506855f584b
