### ISSUE TITLE
caculating word vector distance or similarity

### ISSUE THREAD

**Issue by chickenbestlover** [spro/practical-pytorch#17]
Hello,

Thank you for the excellent practice codes.

For the **closest** function in glove tutorial,
I suggest that we can use inner product as a similarity between two vectors like this:

```python
def closest2(d, n=10):
    all_dists = [(w, torch.mul(d, get_word(w)).sum()) for w in wv_dict]
    sorted_dists = sorted(all_dists, reverse=True, key=lambda t: t[1])[:n]
    return sorted_dists
```

It is slightly faster than calculating the distance between two vectors.

Regards,

**Comment by spro** [comment]
Thanks, It does work a little faster but I think the results are not as good for analogies -

```
analogy(building : architect :: software : ?)
(5.8369) programmer
(6.8881) entrepreneur
(6.9240) inventor
(6.9730) developer
(6.9949) innovator

analogy2(building : architect :: software : ?)
(28.9717) computer
(28.0493) microsoft
(27.9680) programmer
(27.2747) browser
(26.1875) pc
```

Possibly because it loses information about the magnitude of the difference.
