### ISSUE TITLE
hello, I have encountered some new questions about Attention mechanism

### ISSUE THREAD

**Issue by czs0x55aa** [spro/practical-pytorch#18]
First, thanks again for your tutorial code.

I read the paper "NEURAL MACHINE TRANSLATIONBY JOINTLY LEARNING TO ALIGN AND TRANSLATE". The description of the attention model is different from your code.

In your code, use`decoder pre hidden` and `target input` as inputs to calculate the `attn weights`.
However, in this paper, it seems use `decoder pre hidden` and `encoder hidden state` to calculate the weights(see Eq.(6)).
I'm not sure my understanding is correct.

Could you please tell me why?
Thank!

**Comment by spro** [comment]
See my comment in #16, the biggest difference is I am using last decoder output and decoder hidden state, while they use last decoder hidden state and encoder outputs. The paper also incorporates this "context" vector into several places. I do plan on updating it soon, to bring it closer to the paper.

**Comment by spro** [comment]
The tutorial has been updated to match the paper from Luong et al [Effective Approaches to Attention-based Neural Machine Translation](https://arxiv.org/abs/1508.04025) and also explain the model from the original paper more clearly
