### ISSUE TITLE
Running the code without attention mechanism

### ISSUE THREAD

**Issue by meghdadFar** [spro/practical-pytorch#19]
I am trying to change the decoder from AttnDecoderRNN to DecoderRNN and have the program work after this change. I adjust the input arguments when creating the model. However, I get the following error that occurs while training the model in train() function.  

The call that causes the error:
```
decoder_output, decoder_hidden, decoder_attention = decoder(
                decoder_input, decoder_hidden, encoder_output, encoder_outputs)
```

The error:
```
in __call__
result = self.forward(*input, **kwargs)
TypeError: forward() takes exactly 3 arguments (5 given) 
```

**Comment by meghdadFar** [comment]
Turns out 
```
decoder_output, decoder_hidden, decoder_attention = decoder(
                decoder_input, decoder_hidden, encoder_output, encoder_outputs)
```
Has to be changed to: 
```
decoder_output, decoder_hidden = decoder(
                decoder_input, decoder_hidden)
```
Seems obvious, but I didn't see where forward() is called in the first place.

**Comment by spro** [comment]
Calling `decoder(...)` is a shortcut for `decoder.forward(...)`

**Comment by meghdadFar** [comment]
That's true. Thanks!
