### ISSUE TITLE
char-nn-classification.pt file

### ISSUE THREAD

**Issue by amhajavi** [spro/practical-pytorch#2]
Hi there,
I was just wandering around with the code trying to install and run it. I just reached the running part and got error " No such file or directory: 'char-rnn-classification.pt' " trying to run your first example "python predict.py Hinton "
I'm not sure if it fits here maybe I'm missing something I just wanted to know how to overcome this?!

**Comment by spro** [comment]
You should run train.py first to create that file.

**Comment by amhajavi** [comment]
great thanks, 
How ever for python2 the # -*- coding: utf-8 -*- is missing on top of train.py added it and it works perfectly fine. awesome work done @spro .

**Comment by spro** [comment]
Good to know, only tried it with python3 so far. Thanks!
