### ISSUE TITLE
Dimension error in default setting

### ISSUE THREAD

**Issue by sangwoomo** [spro/practical-pytorch#22]
Hi, I tried to run the code, but found a dimension error.
I changed output dimension in train function, and it worked well.
I modified `output.view(-1)` to `output.view(1,-1)`.
The full error message is attached below.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-13b1ca4eca46> in <module>()
     15 
     16 for epoch in range(1, n_epochs + 1):
---> 17     loss = train(*random_training_set())
     18     loss_avg += loss
     19 

<ipython-input-16-e56fe7ed3c3d> in train(inp, target)
      6     for c in range(chunk_len):
      7         output, hidden = decoder(inp[c], hidden)
----> 8         loss += criterion(output.view(-1), target[c])
      9 
     10     loss.backward()

/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    204 
    205     def __call__(self, *input, **kwargs):
--> 206         result = self.forward(*input, **kwargs)
    207         for hook in self._forward_hooks.values():
    208             hook_result = hook(self, input, result)

/anaconda/lib/python3.6/site-packages/torch/nn/modules/loss.py in forward(self, input, target)
    319         _assert_no_grad(target)
    320         return F.cross_entropy(input, target,
--> 321                                self.weight, self.size_average)
    322 
    323 

/anaconda/lib/python3.6/site-packages/torch/nn/functional.py in cross_entropy(input, target, weight, size_average)
    531                 for each minibatch.
    532     """
--> 533     return nll_loss(log_softmax(input), target, weight, size_average)
    534 
    535 

/anaconda/lib/python3.6/site-packages/torch/nn/functional.py in nll_loss(input, target, weight, size_average)
    498         f = _functions.thnn.NLLLoss2d(size_average, weight=weight)
    499     else:
--> 500         raise ValueError('Expected 2 or 4 dimensions (got {})'.format(dim))
    501     return f(input, target)
    502 

ValueError: Expected 2 or 4 dimensions (got 1)

**Comment by spro** [comment]
Thanks, turns out that `.view` is not necessary at all (the shape is already `1 x N`).
