### ISSUE TITLE
Bahdanau Decoder Implementation

### ISSUE THREAD

**Issue by dyngts** [spro/practical-pytorch#23]
Hi @spro,

Thanks for really great explanation of decoder, especially for Bahdanau decoder. But, i'm little bit confuse about code in __init__ function of BahdanauAttnDecoderRNN class.

```
self.attn = GeneralAttn(hidden_size)
```

I can't find any class that define **GeneralAttn**. This is built-in class? Can you please elaborate for this? Thanks again!

**Comment by spro** [comment]
Good catch, it was originally split out as 3 separate attention modules (GeneralAttn, DotAttn, ConcatAttn) instead of one with an argument to choose the strategy. Further, they actually used the "concat" strategy. So this should be `self.attn = Attn("concat", hidden_size)`

**Comment by dyngts** [comment]
Cool, Thanks for the clarification!

**Comment by quoniammm** [comment]
The `GeneralAttn` is not defined.Why it can be run.I can not understand it.
Could you tell me why?@Spro@dyngts

**Comment by rafaelvalle** [comment]
Can you please change that line on the notebook?

**Comment by poweihuang17** [comment]
Still not changed. Hope somebody could do it.

**Comment by anantzoid** [comment]
#119  fixes this and some more issues with Bahdanau decoder.

**Comment by kyquang97** [comment]
@anantzoid  it's still not fixes in tutorial. 
![image](https://user-images.githubusercontent.com/17948800/57349699-498bd280-7185-11e9-85f4-21cdd7c67235.png)
