### ISSUE TITLE
Doubling input size by two in decoder

### ISSUE THREAD

**Issue by dyngts** [spro/practical-pytorch#24]
Hi @spro,

I still don't get the point why you double the input size by two when initiating attention decoder, RNN layer, and output

```
self.attn = nn.Linear(self.hidden_size * 2, hidden_size)
```

```
self.gru = nn.GRU(hidden_size * 2, hidden_size, n_layers, dropout=dropout_p)
```

```
self.out = nn.Linear(hidden_size * 2, output_size)
```

Can you please elaborate more about this? Thank you!

**Comment by spro** [comment]
Each of those layers operate on a concatenation of two `hidden_size` sized vectors - the attention layer uses hidden state and encoder output (in the concat case); the GRU uses the embedded word and the last attention context; the output layer uses the GRU output and current attention context. These all give the layers some extra information to calculate their outputs with.

**Comment by dyngts** [comment]
Thanks for the clear explanation, now it's totally make sense!
