### ISSUE TITLE
Cuda transfer

### ISSUE THREAD

**Issue by ManniSingh** [spro/practical-pytorch#3]
Hi, 
thanks for the tuutorial, Could you let me know how can i process the "seq2seq-translation" code on the GPU. I tried putting objects -"encoder1" and "attn_decoder1" using ".cuda()" with no success. 
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)

**Comment by spro** [comment]
You will have to convert the data Tensors/Variables as well - I have not yet tried on CUDA so I'm not 100% sure. Let me know if you make any progress.

**Comment by ManniSingh** [comment]
In the tutorial(deep learning with PyTorch), the instance("net") is moved to GPU using ".cuda()" which did not work as i mentioned earlier. 
So, I tried to move tensors to GPU within the class, starting from "EncoderRNN" class, 
For example,
output.data = output.data.cuda()
But, still no success

**Comment by pabloloyola** [comment]
Hi, I managed to transfer to gpu, but I think it may not be the most elegant way to do it.
Basically I had to add .cuda() on eight parts : 

-2 for the network objects
-2 for the hidden states initialization
-2 in the variablesFromPair method, for input and output
- in the train method, one for  encoder_outputs  and decoder_input 

You can see it here  (im using python 2.7): 
https://gist.github.com/pabloloyola/b2e316be2efa7f04bea2a4a9cf3ee144

Lets see if there is a better way ;)

**Comment by spro** [comment]
Awesome, thanks @pabloloyola. Have you compared timing to CPU?

**Comment by ManniSingh** [comment]
Thanks @pabloloyola , 
BTW, did you manaage to run it? 
I am getting : "RuntimeError: could not compute gradients for some functions (CudnnRNN)"

**Comment by spro** [comment]
If you got that CudnnRNN error (could not compute gradients for some functions) it should be fixed in the latest version of PyTorch, 0.1.9
