### ISSUE TITLE
Edit: decoder --> encoder

### ISSUE THREAD

**Issue by meghdadFar** [spro/practical-pytorch#30]
Not sure this is actually an issue. It is only a typo. But it also exists here:
http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

In Training --> Defining a training iteration --> Next the decoder is given the last hidden state of the `decoder` as its first hidden state, and the <SOS> token as its first input.  

Shouldn't it become the following?

Next the decoder is given the last hidden state of the `encoder` as its first hidden state, and the <SOS> token as its first input.

**Comment by meghdadFar** [comment]
Looking back at this problem again, in method `train()` shouldn't 
`decoder_hidden = encoder_hidden` 
become 
`decoder_hidden = encoder_output`

I believe the context vector that has to be fed to the decoder is only generated as the last output of the encoder. The hidden states of the encoder are used to model dependencies between the words of a sequence.

**Comment by spro** [comment]
Yeah the first thing is a typo, thanks. The second is on purpose - the main difference between the encoder output and hidden state is that the output covers each step from the last encoder layer, while the hidden state is the final step of all encoder layers. So in this case the last state of all encoder layers are brought over to the first state of all decoder layers.

**Comment by ehsanasgari** [comment]
So would you confirm that in both train and evaluate functions the following fixing is needed?

decoder_hidden = encoder_output

instead of 

decoder_hidden = encoder_hidden

**Comment by spro** [comment]
No only the typo in the text above, the code is right.

**Comment by meghdadFar** [comment]
That's right.
