### ISSUE TITLE
jupiter notebook error

### ISSUE THREAD

**Issue by mpicci** [spro/practical-pytorch#32]
I'm getting this strange error running the reinforce-gridworld notebook.
But not another machine with almost the same conda installation run without problem!
Any guess?

Thank you
Marco

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-17b9c3497d5b> in <module>()
      1 env = Environment()
----> 2 env.reset()
      3 print(env.visible_state)
      4 
      5 done = False

<ipython-input-4-6685230fcd4b> in reset(self)
     13         self.t = 0
     14         self.history = []
---> 15         self.record_step()
     16 
     17         return self.visible_state

<ipython-input-4-6685230fcd4b> in record_step(self)
     20         """Add the current state to history for display later"""
     21         grid = np.array(self.grid.grid)
---> 22         grid[self.agent.pos] = self.agent.health * 0.5 # Agent marker faded by health
     23         visible = np.array(self.grid.visible(self.agent.pos))
     24         self.history.append((grid, visible, self.agent.health))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by spro** [comment]
Looks like a problem indexing with the `pos` tuple. I tried looking through numpy docs for clues but they claim not to support tuple indexing at all.

What are the python and numpy versions on the two machines?

**Comment by mpicci** [comment]
These are the output of conda list on the two machines, both ubuntu 16.04
[working_machine.txt](https://github.com/spro/practical-pytorch/files/1062052/working_machine.txt)
[not_working-machine.txt](https://github.com/spro/practical-pytorch/files/1062057/not_working-machine.txt)

**Comment by spro** [comment]
Beyond numpy versions I'm not sure what to look for, but above fix should work in either environments. Let me know if that works.

**Comment by mpicci** [comment]
I think I find the problem, it's about self.agent.pos
It returns float values used as indices on grid

**Comment by mpicci** [comment]
I made it work!
just make sure that c is integer! math.floor return 4.0 a not integer value

**Comment by spro** [comment]
Good find, thank you!
