### ISSUE TITLE
Regarding exercises in Character-Level RNN

### ISSUE THREAD

**Issue by oya163** [spro/practical-pytorch#35]
I was wondering where I can find the dataset for the exercises given in Classifying Names with Character-Level RNN.
For example:
    Any word -> language
    First name -> gender
    Character name -> writer
    Page title -> blog or subreddit

To complete this task, do I have to create my own dataset or is there any repo where I can download that dataset?

**Comment by spro** [comment]
Those are just ideas to try with your own datasets. For the reddit one I suggest https://github.com/linanqiu/reddit-dataset

**Comment by oya163** [comment]
Thank you very much spro.
