### ISSUE TITLE
Why RELU is used in the input of Decoder?

### ISSUE THREAD

**Issue by CodePothunter** [spro/practical-pytorch#4]
Hello, thank you for your codes and notes.

I have a question about "Practical PyTorch: Translation with a Sequence to Sequence Network and Attention", where the "simple decoder" uses a RELU after input embedding. Why did you add an activation function between input embedding and GRU? Is it a trick? Thank you

**Comment by spro** [comment]
After training with and without the ReLU layer a few times, it looks like there is no significant difference, so I'll remove it for simplicity.

**Comment by CodePothunter** [comment]
Thanks for response!
