### ISSUE TITLE
#seq2seq-translation set up optimizer for encoder and decoder together rather than separately?

### ISSUE THREAD

**Issue by moonlightlane** [spro/practical-pytorch#55]
Hi there, 

This is more a question rather than issue... I was writing the seq2seq model as a single class that combine the encoder and decoder class. Writing this way, I can simply set up an optimizer for the entire seq2seq class like this: `optimizer = optim.Adam(seq2seq_model.parameters(), lr=learning_rate)`. Is it OK to do this? In the tutorial I see the optimizers are set up differently for the encoder and the decoder, in that the learning rates are different. Thanks in advance!

**Comment by ryh95** [comment]
Also confused about this

**Comment by hunkim** [comment]
I think we can just do:

```python
params = list(encoder.parameters()) + list(decoder.parameters())
optimizer = torch.optim.Adam(params, lr=0.001)

...
optimizer.step()
```

@moonlightlane what is the seq2seq_model here?

**Comment by spro** [comment]
Using a single optimizer is totally fine, but for the sake of the tutorial they are separate to make it more obvious that the networks themselves are separate. Using different learning rates also leads to better results (though you can also do this with a single optimizer). I'll probably add a disclaimer as many people ask about this.
