### ISSUE TITLE
Update Word Vectors with GloVe tutorial

### ISSUE THREAD

**Issue by notpratheek** [spro/practical-pytorch#60]
Hi ! 

First off, thanks for these amazing set of tutorials ! They are beautiful ! 😄 

It seems like there is lot of changes to the [pytorch/text](https://github.com/pytorch/text) API, compared to what is presented in your [glove-word-vectors](https://github.com/spro/practical-pytorch/blob/master/glove-word-vectors/glove-word-vectors.ipynb) tutorial. 

Could you please update with necessary changes ? I would've definitely sent a pull request, rather than raising the issue, had I know how to make this changes myself ! 😅 

Thanks once again for these great set of tutorials !

**Comment by jongold** [comment]
I just fixed this on a branch, gimme a minute and I'll submit a PR :)

**Comment by notpratheek** [comment]
Works beautifully ! Thank you for the quick update @jongold  and @spro  ! 😃
