### ISSUE TITLE
Error in seq2seq translation

### ISSUE THREAD

**Issue by cmxela** [spro/practical-pytorch#68]
I'm getting an error when executing the notebook. Could be this is a problem with the pytorch version? The error happens in the 'Testing the models' section.

Running python3 and the following version of the packages
torch==0.2.0.post3
torchtext==0.2.0
torchvision==0.1.9

Thanks in advance for any help.

The Log follows...

--------------------------------------------------------------------------------------------------------------------------------
EncoderRNN (
  (embedding): Embedding(10, 10)
  (gru): GRU(10, 10, num_layers=2)
)
AttnDecoderRNN (
  (embedding): Embedding(10, 10)
  (gru): GRU(20, 10, num_layers=2, dropout=0.1)
  (out): Linear (20 -> 10)
  (attn): Attn (
    (attn): Linear (10 -> 10)
  )
)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-d237e3fa1e40> in <module>()
     22 
     23 for i in range(3):
---> 24     decoder_output, decoder_context, decoder_hidden, decoder_attn = decoder_test(word_inputs[i], decoder_context, decoder_hidden, encoder_outputs)
     25     print(decoder_output.size(), decoder_hidden.size(), decoder_attn.size())
     26     decoder_attns[0, i] = decoder_attn.squeeze(0).cpu().data

/home/alexmc/venv/la2/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    222         for hook in self._forward_pre_hooks.values():
    223             hook(self, input)
--> 224         result = self.forward(*input, **kwargs)
    225         for hook in self._forward_hooks.values():
    226             hook_result = hook(self, input, result)

<ipython-input-13-1e8710146be2> in forward(self, word_input, last_context, last_hidden, encoder_outputs)
     30 
     31         # Calculate attention from current RNN state and all encoder outputs; apply to encoder outputs
---> 32         attn_weights = self.attn(rnn_output.squeeze(0), encoder_outputs)
     33         context = attn_weights.bmm(encoder_outputs.transpose(0, 1)) # B x 1 x N
     34 

/home/alexmc/venv/la2/lib/python3.5/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    222         for hook in self._forward_pre_hooks.values():
    223             hook(self, input)
--> 224         result = self.forward(*input, **kwargs)
    225         for hook in self._forward_hooks.values():
    226             hook_result = hook(self, input, result)

<ipython-input-12-3c700c5b6bb1> in forward(self, hidden, encoder_outputs)
     22         # Calculate energies for each encoder output
     23         for i in range(seq_len):
---> 24             attn_energies[i] = self.score(hidden, encoder_outputs[i])
     25 
     26         # Normalize energies to weights in range 0 to 1, resize to 1 x 1 x seq_len

<ipython-input-12-3c700c5b6bb1> in score(self, hidden, encoder_output)
     35         elif self.method == 'general':
     36             energy = self.attn(encoder_output)
---> 37             energy = hidden.dot(energy)
     38             return energy
     39 

/home/alexmc/venv/la2/lib/python3.5/site-packages/torch/autograd/variable.py in dot(self, other)
    629 
    630     def dot(self, other):
--> 631         return Dot.apply(self, other)
    632 
    633     def _addcop(self, op, args, inplace):

/home/alexmc/venv/la2/lib/python3.5/site-packages/torch/autograd/_functions/blas.py in forward(ctx, vector1, vector2)
    209         ctx.save_for_backward(vector1, vector2)
    210         ctx.sizes = (vector1.size(), vector2.size())
--> 211         return vector1.new((vector1.dot(vector2),))
    212 
    213     @staticmethod

RuntimeError: Expected argument self to have 1 dimension(s), but has 2 at /pytorch/torch/csrc/generic/TensorMethods.cpp:23020

**Comment by cmxela** [comment]
Sorry, I have seen the problem has already been reported and answered

**Comment by renato145** [comment]
I made some changes in my code that seems to work:

First, I'm calling the attention layer like this:
`att_weights = self.attention(rnn_output, encoder_outputs)`
(instead of `attn_weights = self.attn(rnn_output.squeeze(0), encoder_outputs) `)

Then, to call the score function:
`att_energies[b, i] = self.score(hidden[:, b].squeeze(0), encoder_outputs[i, b])`
(instead of `attn_energies[b, i] = self.score(hidden[:, b], encoder_outputs[i, b].unsqueeze(0))`)
