### ISSUE TITLE
embedding question

### ISSUE THREAD

**Issue by birdspring** [spro/practical-pytorch#74]
HI, I got a question about the embedding part in your seq2seq pytorch tutorial. You created two separate embedding matrix for encoder and decoder. Now I want there two matrices are the same. I mean I want the single embedding matrix updated both in the encoder part and decoder part. 
Do you have any suggestions? Thanks.

**Comment by czs0x55aa** [comment]
a simple way as follow：
```python
self.decoder.embedding.weight = self.encoder.embedding.weight
```
