### ISSUE TITLE
Source of name dataset

### ISSUE THREAD

**Issue by Janinanu** [spro/practical-pytorch#94]
Hi! I would like to know where exactly you took the data for the name classification task from. Did you collect the names yourself? 

Thanks a lot!

**Comment by spro** [comment]
Yes they were collected by hand. Unfortunately I didn't save the sources, but names were scraped from the various websites you can find searching for example "russian baby names". I looked for romanized sources to keep the character set small.

**Comment by Janinanu** [comment]
Alright, thanks for your reply!
